# Generated by Django 4.2.2 on 2023-06-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='foto',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
