# Generated by Django 4.2.2 on 2023-06-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_local_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
